name: Test project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20v
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm test
      - run: npm run build
